name: ci/cd

on: [push]

jobs:
  push-images-to-hub:
  
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push GameHavenMain
        uses: docker/build-push-action@v2
        with:
          context: .
          file: GameHavenFront/Dockerfile
          push: true
          tags: jorritdeschaux/gamehaven:front-latest
