name: CI

on: [push]

env:
  AZURE_WEB_APP: 'GameHaven'
  DOCKER_IMAGE_NAME: 'jorritdeschaux/gamehaven'
jobs:

  push-images:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push GameHavenFront
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jorritdeschaux/gamehaven:front-latest
        
  deploy:
      needs: push-images
      runs-on: ubuntu-latest
      steps:  
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Azure WebApp Deployment
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: '${{env.AZURE_WEB_APP}}'
          # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
          images: '${{secrets.DOCKER_LOGIN}}/${{env.DOCKER_IMAGE_NAME}}:front-latest'
